# -*- coding: utf-8 -*-
"""Final Project - CS2704 - 3713401

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11J8qBFBL-27k7RbMtK11mZCYJowzzC3e
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

file_path = 'filtered-energy-consumption-final.xlsx'
file_path2 = 'filtered-CO2Emission.xlsx'

df = pd.read_excel(file_path)
df2 = pd.read_excel(file_path2)

print(df)
print(df2)

import pandas as pd

file_path = 'fossil-fuel-primary-energy-final.csv'
df = pd.read_csv(file_path)

filtered_df = df[df['Entity'].str.contains('(EI)')]

filtered_file_path = 'filtered-energy-consumption.xlsx'
filtered_df.to_excel(filtered_file_path, index=False)

print(filtered_df)

import pandas as pd

file_path = 'annual-co-emissions-by-region-final.csv'
df = pd.read_csv(file_path)

df = df[df['Entity'].str.contains('(GCP)')]
df = df[df['Year'] >= 1965]

filtered_file_path = 'filtered-CO2Emission.xlsx'
df.to_excel(filtered_file_path, index=False)
print(df)

import pandas as pd

file_path = 'filtered-energy-consumption.xlsx'
df = pd.read_excel(file_path)

df['Entity'] = df['Entity'].str.replace('\(GCP\)','GCP',regex=True)

df = df[df['Year'] >= 1965]

output_file_path = 'filtered-energy-consumption-final.xlsx'
df.to_excel(output_file_path, index=False)

print(f'Modified data saved to {output_file_path}')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import linregress

file_path_energy = 'filtered-energy-consumption-final.xlsx'
file_path_co2 = 'filtered-CO2Emission.xlsx'

df_energy = pd.read_excel(file_path_energy)

df_co2 = pd.read_excel(file_path_co2)

df = pd.merge(df_energy, df_co2, on=['Entity', 'Year'])

slope, intercept, r_value, p_value, std_err = linregress(df['EnergyConsumption'], df['CO2Emissions'])

plt.figure(figsize=(10, 6))
plt.scatter(df['EnergyConsumption'], df['CO2Emissions'], label='Data')
plt.title('Scatter Plot: Energy Consumption vs CO2 Emissions')
plt.xlabel('Energy Consumption')
plt.ylabel('CO2 Emissions')

plt.plot(df['EnergyConsumption'], slope * df['EnergyConsumption'] + intercept, color='red', label='Linear Regression')

plt.legend()
plt.show()

print(f'Linear Regression Equation: y = {slope:.2f}x + {intercept:.2f}')
print(f'Pearson correlation coefficient: {r_value:.2f}')
print(f'P-value: {p_value:.2e}')

import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import pearsonr

df_co2 = pd.read_excel('filtered-CO2Emission.xlsx')
df_energy = pd.read_excel('filtered-energy-consumption-final.xlsx')

df_merged = pd.merge(df_co2, df_energy, on=['Entity', 'Year'])

x = df_merged['EnergyConsumption']
y = df_merged['CO2Emissions']

plt.scatter(x, y, alpha=0.5)
plt.title('Energy Consumption vs CO2 Emission')
plt.xlabel('Energy Consumption')
plt.ylabel('CO2 Emission')

corr_coefficient, p_value = pearsonr(x, y)
print(f'Correlation Coefficient: {corr_coefficient}')
print(f'P-Value: {p_value}')

plt.show()

import pandas as pd
import matplotlib.pyplot as plt

file_path = 'filtered-CO2Emission.xlsx'
file_path2 = 'filtered-energy-consumption-final.xlsx'

df_emissions = pd.read_excel(file_path)
df_consumption = pd.read_excel(file_path2)

plt.figure(figsize=(10, 6))
plt.bar(df_emissions['Year'], df_emissions['CO2Emissions'], color='blue')
plt.title('CO2 Emission per Year')
plt.xlabel('Year')
plt.ylabel('CO2 Emission')
plt.show()

plt.figure(figsize=(10, 6))
plt.bar(df_consumption['Year'], df_consumption['EnergyConsumption'], color='green')
plt.title('Energy Consumption per Year')
plt.xlabel('Year')
plt.ylabel('Energy Consumption')
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

file_path_emissions = '/content/filtered-CO2Emission.xlsx'
df_emissions = pd.read_excel(file_path_emissions)
file_path_energy = '/content/filtered-energy-consumption-final.xlsx'
df_energy = pd.read_excel(file_path_energy)

df_merged = pd.merge(df_emissions, df_energy, on=['Entity', 'Year'])

plt.figure(figsize=(12, 8))

sns.scatterplot(data=df_merged, x='EnergyConsumption', y='CO2Emissions', hue='Entity', palette='viridis', s=100)
plt.title('CO2 Emission vs Energy Consumption')
plt.xlabel('Energy Consumption')
plt.ylabel('CO2 Emission')
plt.legend(title='Region', bbox_to_anchor=(1, 1))
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

file_path_emissions = '/content/filtered-CO2Emission.xlsx'
df_emissions = pd.read_excel(file_path_emissions)
file_path_energy = '/content/filtered-energy-consumption-final.xlsx'
df_energy = pd.read_excel(file_path_energy)

df_merged = pd.merge(df_emissions, df_energy, on=['Year', 'Entity'])

df_corr = df_merged[['CO2Emissions', 'EnergyConsumption']]

correlation_matrix = df_corr.corr()

plt.figure(figsize=(8, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Heatmap: CO2 Emission vs Energy Consumption')
plt.show()
